-- ==============================================================================
-- INFINITE SOFTWARE FACTORY: COMPREHENSIVE SUPABASE INITIALIZATION SCHEMA
-- ==============================================================================
-- This script is completely idempotent. You can safely run it multiple times.

-- ==============================================================================
-- 1. EXTENSIONS
-- ==============================================================================
CREATE EXTENSION IF NOT EXISTS vector;

-- ==============================================================================
-- 2. SCHEMAS
-- ==============================================================================
CREATE SCHEMA IF NOT EXISTS app_dev;
CREATE SCHEMA IF NOT EXISTS app_stage;
CREATE SCHEMA IF NOT EXISTS app_prod;

-- ==============================================================================
-- 3. CORE: Chat Sessions & Telegram Integration
-- ==============================================================================
CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,
    title TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    agent_context JSONB DEFAULT '{}'::jsonb,
    status TEXT NOT NULL DEFAULT 'completed'
        CHECK (status IN ('wip', 'unread', 'completed', 'kiv', 'trashed', 'archived')),
    last_run_mode TEXT DEFAULT 'P',
    tags TEXT DEFAULT '[]',
    color TEXT DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS idx_sessions_status ON sessions(status);
CREATE INDEX IF NOT EXISTS idx_sessions_tags ON sessions(tags);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT REFERENCES sessions(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system', 'tool', 'ai')),
    content TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    image TEXT,
    images JSONB DEFAULT '[]'::jsonb,
    tool_calls JSONB DEFAULT '[]'::jsonb,
    token_in BIGINT DEFAULT 0,
    token_out BIGINT DEFAULT 0,
    cost REAL DEFAULT 0.0,
    cache_hit BIGINT DEFAULT 0,
    cache_miss BIGINT DEFAULT 0,
    model TEXT,
    run_mode TEXT
);

CREATE TABLE IF NOT EXISTS token_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT,
    model TEXT,
    token_in BIGINT DEFAULT 0,
    token_out BIGINT DEFAULT 0,
    cache_hit BIGINT DEFAULT 0,
    cache_miss BIGINT DEFAULT 0,
    cost REAL DEFAULT 0.0,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS token_usage_hourly (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hour_bucket TEXT NOT NULL,
    model TEXT NOT NULL,
    token_in BIGINT DEFAULT 0,
    token_out BIGINT DEFAULT 0,
    cache_hit BIGINT DEFAULT 0,
    cache_miss BIGINT DEFAULT 0,
    cost REAL DEFAULT 0.0,
    request_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    CONSTRAINT uq_token_usage_hourly_bucket_model UNIQUE (hour_bucket, model)
);

CREATE INDEX IF NOT EXISTS idx_token_usage_hourly_bucket
    ON token_usage_hourly (hour_bucket);

CREATE INDEX IF NOT EXISTS idx_token_usage_hourly_model
    ON token_usage_hourly (model);

CREATE TABLE IF NOT EXISTS telegram_sessions (
    telegram_user_id BIGINT PRIMARY KEY,
    session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS telegram_message_map (
    message_id BIGINT PRIMARY KEY,
    session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==============================================================================
-- 4. BROWSER AUTOMATION RECORDS
-- ==============================================================================
-- ==============================================================================
-- 5. SYSTEM OBSERVABILITY & WORKFLOWS
-- ==============================================================================
CREATE TABLE IF NOT EXISTS audit_trail (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    trace_id UUID NOT NULL, 
    request_id UUID, 
    step_phase TEXT NOT NULL, 
    actor TEXT NOT NULL, 
    environment TEXT NOT NULL CHECK (environment IN ('dev', 'stage', 'prod', 'system')),
    input_context TEXT, 
    output_artifact TEXT, 
    reasoning TEXT, 
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS system_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_container TEXT NOT NULL, 
    level TEXT NOT NULL CHECK (level IN ('INFO', 'WARNING', 'ERROR', 'DEBUG', 'CRITICAL')),
    message TEXT NOT NULL,
    latency_ms REAL, 
    status_code INTEGER, 
    metadata JSONB DEFAULT '{}'::jsonb, 
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS change_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'in_progress', 'completed', 'failed')),
    priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),
    source TEXT NOT NULL CHECK (source IN ('user', 'growth_agent', 'log_monitor', 'developer')),
    generated_proposal JSONB, 
    approver_id UUID, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    trace_id UUID 
);

-- ==============================================================================
-- 6. DB AGENT ADMIN & SEMANTIC ENGINE
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.agent_nodes (
    id SERIAL PRIMARY KEY,
    node_name VARCHAR(255) NOT NULL,
    api_endpoint_url TEXT NOT NULL,
    encrypted_auth_token TEXT, 
    domain_description TEXT NOT NULL, 
    is_enabled BOOLEAN DEFAULT TRUE,
    cached_schema JSONB,
    dialect VARCHAR(50) DEFAULT 'PostgreSQL',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.semantic_definitions (
    id SERIAL PRIMARY KEY,
    node_id INTEGER REFERENCES public.agent_nodes(id) ON DELETE CASCADE,
    definition_type VARCHAR(50) NOT NULL, -- 'TABLE' or 'COLUMN'
    physical_name VARCHAR(255) NOT NULL,
    parent_name VARCHAR(255), -- e.g., table name for a column
    ai_generated_description TEXT,
    human_override_description TEXT,
    business_rules TEXT, -- For enum mappings like {"1": "Active"}
    status VARCHAR(50) DEFAULT 'AI_LEARNED',
    embedding vector(768),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- HNSW index for fast similarity search (Cosine distance)
CREATE INDEX IF NOT EXISTS idx_semantic_definitions_embedding
ON semantic_definitions USING hnsw (embedding vector_cosine_ops);

-- RPC for matching schema definitions
CREATE OR REPLACE FUNCTION match_schema_definitions(
    query_embedding vector(768),
    match_threshold float,
    match_count int,
    p_node_id int DEFAULT NULL
)
RETURNS TABLE (
    id int,
    physical_name text,
    ai_generated_description text,
    human_override_description text,
    status text,
    similarity float
)
LANGUAGE plpgsql STABLE AS $$
BEGIN
    RETURN QUERY
    SELECT
        sd.id,
        sd.physical_name::text,
        sd.ai_generated_description,
        sd.human_override_description,
        sd.status::text,
        1 - (sd.embedding <=> query_embedding) AS similarity
    FROM semantic_definitions sd
    WHERE sd.embedding IS NOT NULL
      AND (p_node_id IS NULL OR sd.node_id = p_node_id)
      AND sd.status IN ('AI_LEARNED', 'HUMAN_OVERRIDE')
      AND 1 - (sd.embedding <=> query_embedding) > match_threshold
    ORDER BY sd.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;

-- ==============================================================================
-- 7. BROWSER CREDENTIALS VAULT
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.browser_credentials (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain text NOT NULL,
    environment text NOT NULL DEFAULT 'production',
    username text NOT NULL,
    password_encrypted text NOT NULL,
    input_schema jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT browser_credentials_domain_environment_username_key UNIQUE (domain, environment, username)
);

-- ==============================================================================
-- 9. RULES GOVERNANCE & TELEMETRY
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.rule_health (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_name character varying(255) NOT NULL UNIQUE,
    success_count integer DEFAULT 0,
    failure_count integer DEFAULT 0,
    missed_count integer DEFAULT 0,
    status character varying(50) DEFAULT 'active',
    last_evaluated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.rule_evaluation_audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id character varying(255),
    turn_index integer,
    rule_name character varying(255),
    scenario character varying(50) NOT NULL,
    score_delta integer DEFAULT 0,
    reasoning text,
    injected_rules text,
    user_prompt text,
    thinking_process jsonb,
    ai_response text,
    step_count integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.rule_deficit_recommendations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id character varying(255),
    turn_index integer,
    user_prompt text,
    thinking_process jsonb,
    step_count integer,
    ai_response text,
    reasoning text,
    suggested_draft text,
    status character varying(50) DEFAULT 'pending',
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

-- ==============================================================================
-- 10. AUDIT LOGGING
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.db_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name character varying(255) NOT NULL,
    record_id bigint NOT NULL,
    action character varying(50) NOT NULL,
    old_value jsonb,
    new_value jsonb,
    updated_by uuid REFERENCES auth.users(id),
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- ==============================================================================
-- 11. ROW LEVEL SECURITY (RLS) & POLICIES
-- ==============================================================================
-- Enable RLS
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE token_usage_hourly ENABLE ROW LEVEL SECURITY;
ALTER TABLE telegram_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE telegram_message_map ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_trail ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE change_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_nodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.semantic_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.browser_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rule_health ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rule_evaluation_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rule_deficit_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.db_audit_logs ENABLE ROW LEVEL SECURITY;

-- Idempotent Policies
DO $$
BEGIN
    DROP POLICY IF EXISTS "Enable all for service role on messages" ON messages;
    DROP POLICY IF EXISTS "Allow full access for service_role on token_usage_hourly" ON public.token_usage_hourly;
    DROP POLICY IF EXISTS "Enable all for service role on telegram_sessions" ON telegram_sessions;
    DROP POLICY IF EXISTS "Enable all for service role on telegram_message_map" ON telegram_message_map;
    DROP POLICY IF EXISTS "Enable all for service role on audit_trail" ON audit_trail;
    DROP POLICY IF EXISTS "Enable all for service role on system_logs" ON system_logs;
    DROP POLICY IF EXISTS "Enable all for service role on change_requests" ON change_requests;
    DROP POLICY IF EXISTS "Allow full access for service_role on agent_nodes" ON public.agent_nodes;
    DROP POLICY IF EXISTS "Allow full access for service_role on semantic_definitions" ON public.semantic_definitions;
    DROP POLICY IF EXISTS "Allow full access for service_role on browser_credentials" ON public.browser_credentials;
    DROP POLICY IF EXISTS "Allow full access for service_role on rule_health" ON public.rule_health;
    DROP POLICY IF EXISTS "Allow full access for service_role on rule_evaluation_audit_log" ON public.rule_evaluation_audit_log;
    DROP POLICY IF EXISTS "Allow full access for service_role on rule_deficit_recommendations" ON public.rule_deficit_recommendations;
    DROP POLICY IF EXISTS "Allow full access for service_role on db_audit_logs" ON public.db_audit_logs;
END $$;

CREATE POLICY "Enable all for service role on messages" ON messages FOR ALL USING (true);
CREATE POLICY "Allow full access for service_role on token_usage_hourly" ON public.token_usage_hourly FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for service role on telegram_sessions" ON telegram_sessions FOR ALL USING (true);
CREATE POLICY "Enable all for service role on telegram_message_map" ON telegram_message_map FOR ALL USING (true);
CREATE POLICY "Enable all for service role on audit_trail" ON audit_trail FOR ALL USING (true);
CREATE POLICY "Enable all for service role on system_logs" ON system_logs FOR ALL USING (true);
CREATE POLICY "Enable all for service role on change_requests" ON change_requests FOR ALL USING (true);
CREATE POLICY "Allow full access for service_role on agent_nodes" ON public.agent_nodes FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Allow full access for service_role on semantic_definitions" ON public.semantic_definitions FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Allow full access for service_role on browser_credentials" ON public.browser_credentials FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Allow full access for service_role on rule_health" ON public.rule_health FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Allow full access for service_role on rule_evaluation_audit_log" ON public.rule_evaluation_audit_log FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Allow full access for service_role on rule_deficit_recommendations" ON public.rule_deficit_recommendations FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Allow full access for service_role on db_audit_logs" ON public.db_audit_logs FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ==============================================================================
-- 12. GRANTS & PERMISSIONS
-- ==============================================================================
GRANT USAGE ON SCHEMA app_dev TO authenticated, service_role;
GRANT USAGE ON SCHEMA app_stage TO authenticated, service_role;
GRANT USAGE ON SCHEMA app_prod TO authenticated, service_role;

GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- ==============================================================================
-- 13. CRON SCHEDULING SYSTEM
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.cron_scheduled_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    cron_expression VARCHAR(50) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    job_type VARCHAR(50) DEFAULT 'Cron_Daemon' NOT NULL,
    target_type VARCHAR(50) DEFAULT 'HTTP_WEBHOOK' NOT NULL,
    target_payload JSONB DEFAULT '{}'::jsonb NOT NULL,
    version INTEGER DEFAULT 1 NOT NULL,
    created_by UUID REFERENCES auth.users(id),
    updated_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT chk_job_type CHECK (job_type IN ('Cron_Daemon', 'PG_CRON')),
    CONSTRAINT chk_target_type CHECK (target_type IN ('HTTP_WEBHOOK', 'SQL_FUNCTION', 'ISOLATED_PROCESS'))
);

CREATE TABLE IF NOT EXISTS public.cron_job_execution_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES public.cron_scheduled_jobs(id) ON DELETE CASCADE,
    status VARCHAR(50) NOT NULL,
    started_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    completed_at TIMESTAMPTZ,
    duration_ms BIGINT,
    error_message TEXT,
    response_payload JSONB,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

ALTER TABLE public.cron_scheduled_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cron_job_execution_logs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    DROP POLICY IF EXISTS "Allow full access for service_role on cron_scheduled_jobs" ON public.cron_scheduled_jobs;
    DROP POLICY IF EXISTS "Allow full access for service_role on cron_job_execution_logs" ON public.cron_job_execution_logs;
END $$;

CREATE POLICY "Allow full access for service_role on cron_scheduled_jobs" ON public.cron_scheduled_jobs FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Allow full access for service_role on cron_job_execution_logs" ON public.cron_job_execution_logs FOR ALL TO service_role USING (true) WITH CHECK (true);
